name: my_portfolio
description: My Flutter Portfolio
publish_to: "none"
version: 1.1.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  go_router: ^4.2.8
  rxdart: ^0.27.5
  super_banners: ^0.0.1
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/projects/
    - assets/articles/
    - assets/icons/
  fonts:
    - family: MyPortfolio
      fonts:
        - asset: fonts/MyPortfolio.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
