name: my_portfolio
description: My Flutter Portfolio
publish_to: "none"
version: 1.2.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_blurhash: ^0.7.0
  go_router: ^6.0.1
  rxdart: ^0.27.7
  seo_renderer: ^0.6.0
  super_banners: ^0.0.1
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: MyPortfolio
      fonts:
        - asset: fonts/MyPortfolio.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
