name: my_portfolio
description: My Flutter Portfolio
publish_to: "none"
version: 1.6.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dio: ^5.1.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^2.2.0
  go_router: ^7.0.0
  intl: ^0.18.0
  json_annotation: ^4.8.1
  seo_renderer: ^0.6.0
  shimmer: ^2.0.0
  super_banners: ^0.0.1
  url_launcher: ^6.1.11

dev_dependencies:
  build_runner: ^2.4.2
  fd_lints: ^1.0.2
  flutter_test:
    sdk: flutter
  freezed: ^2.3.3
  json_serializable: ^6.6.1

flutter:
  uses-material-design: false
  fonts:
    - family: MyPortfolio
      fonts:
        - asset: fonts/MyPortfolio.ttf
