name: my_portfolio
description: My Flutter Portfolio
publish_to: "none"
version: 1.5.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dio: ^5.1.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.2
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^2.2.0
  go_router: ^6.5.2
  intl: ^0.17.0
  json_annotation: ^4.8.0
  seo_renderer: ^0.6.0
  shimmer: ^2.0.0
  super_banners: ^0.0.1
  url_launcher: ^6.1.10

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: false
  fonts:
    - family: MyPortfolio
      fonts:
        - asset: fonts/MyPortfolio.ttf
